# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  # adapter: sqlite3 OLD
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: flatiron_mod3_development
  #  database: db/development.sqlite3 OLD


test:
  <<: *default
  # database: db/test.sqlite3 OLD
  database: flatiron_mod3_test

production:
  <<: *default
  # database: db/production.sqlite3 OLD
  database: flat_iron_mod3_production
  
